/*
 * dSS API
 *
 * dSS Server JSON Interface
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: xgcssch@github.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RequestApplicationToken200Response {
    #[serde(rename = "ok", skip_serializing_if = "Option::is_none")]
    pub ok: Option<bool>,
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<crate::models::RequestApplicationToken200ResponseResult>>,
}

impl RequestApplicationToken200Response {
    pub fn new() -> RequestApplicationToken200Response {
        RequestApplicationToken200Response {
            ok: None,
            result: None,
        }
    }
}


