/*
 * dSS API
 *
 * dSS Server JSON Interface
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: xgcssch@github.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SessionTokenResponse {
    #[serde(rename = "ok")]
    pub ok: bool,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<crate::models::SessionTokenResponseAllOfResult>>,
}

impl SessionTokenResponse {
    pub fn new(ok: bool) -> SessionTokenResponse {
        SessionTokenResponse {
            ok,
            message: None,
            result: None,
        }
    }
}


